name: magic-auth-api

services:
  api:
    build:
      context: .
      target: app
    command: 'sh -c "[ -d node_modules ] || npm ci; npm run start:dev"'
    container_name: magic-auth-api
    depends_on:
      - database
    ports:
      - '8082:3000'
    restart: always
    volumes:
      - ./:/app

  database:
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:18.3
    ports:
      - '54322:5432'
    restart: always
    volumes:
      - ./.docker/postgres:/var/lib/postgresql
